/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NesaiNovaRouteImport } from './routes/nesai-nova'
import { Route as NovaPreviewRouteImport } from './routes/nova-preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NesaiNovaRoute = NesaiNovaRouteImport.update({
  id: '/nesai-nova',
  path: '/nesai-nova',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaPreviewRoute = NovaPreviewRouteImport.update({
  id: '/nova-preview',
  path: '/nova-preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nesai-nova': typeof NesaiNovaRoute
  '/nova-preview': typeof NovaPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nesai-nova': typeof NesaiNovaRoute
  '/nova-preview': typeof NovaPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nesai-nova': typeof NesaiNovaRoute
  '/nova-preview': typeof NovaPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/nesai-nova' | '/nova-preview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/nesai-nova' | '/nova-preview'
  id: '__root__' | '/' | '/nesai-nova' | '/nova-preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NesaiNovaRoute: typeof NesaiNovaRoute
  NovaPreviewRoute: typeof NovaPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nesai-nova': {
      id: '/nesai-nova'
      path: '/nesai-nova'
      fullPath: '/nesai-nova'
      preLoaderRoute: typeof NesaiNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-preview': {
      id: '/nova-preview'
      path: '/nova-preview'
      fullPath: '/nova-preview'
      preLoaderRoute: typeof NovaPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NesaiNovaRoute: NesaiNovaRoute,
  NovaPreviewRoute: NovaPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
